stages:
  - build

build_project:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - xcodebuild clean -project breadwallet.xcodeproj -scheme breadwallet | xcpretty
    - xcodebuild test -project breadwallet.xcodeproj -scheme breadwallet -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0' | xcpretty -s
  tags:
    - ios-12
    - xcode-10
    - macos-10_13
